### ISSUE TITLE
Usage with VS Code / Git Authentication

### ISSUE THREAD

**Issue by gatesry** [ndbeals/winssh-pageant#28]
First: Great project, really appreciate the efforts here as it's made my usage of 1Password and agent forwarding actually usable. 

Trying to get VS Code/Git to authenticate to remote repo's hosted on Gitea using private/public keys stored within 1Password. I've tried setting the Remote SSH agent executable, and trying to use Git bash to change the named pipe. But I'm a little over my skies in terms of Googling this one out. 

Any thoughts on what to research or test next?

**Comment by ndbeals** [comment]
Does Vscode/git authentication work on any repos that are hosted elsewhere?

Are you trying to do this from a WSL environment VSCode?

In VSCode, open the terminal and run this command for me `where.exe ssh`. The output should be `C:\Program Files\OpenSSH\ssh.exe` (or something very close).

Because ultimately this isn't actually a `winssh-pageant` issue. VSCode doesn't use pageant at all. That being said I'm still happy to help.

I suspect that VSCode is defaulting to using the `ssh` binary that's bundled with GitForWindows, and not the microsoft OpenSSH `ssh.exe`

**Comment by ndbeals** [comment]
@gatesry were you able to get this to work?
