### ISSUE TITLE
Add and maintain manifest for Scoop installer

### ISSUE THREAD

**Issue by StepanOrt** [ndbeals/winssh-pageant#9]
Scoop is the Windows command-line installer. Could you please add and maintain manifest file for winssh-pageant into the [Scoop Extras repository](https://github.com/lukesampson/scoop-extras)? Thank you.

**Comment by ndbeals** [comment]
Sure, I can do that.

**Comment by ndbeals** [comment]
Scoop manifest is in progress, you can track it at https://github.com/lukesampson/scoop-extras/pull/5864.

**Comment by ndbeals** [comment]
It doesn't seem likely that winssh-pageant will be accepted into the scoop extras repository.

I have already done the work creating the manifest, [found here.](https://gist.github.com/ndbeals/08fd5f1eed011bce2e7bba06da0e5314)

Install it with the following command:
```
scoop install https://gist.githubusercontent.com/ndbeals/08fd5f1eed011bce2e7bba06da0e5314/raw/624cb57ca3fa29acfa3ee0f51aab110fde3d1a1b/winssh-pageant.json
```

I'll update the readme soon.

**Comment by ndbeals** [comment]
Not going to get accepted into scoop, nor am I going to try with scoop again. I may try to get this accepted to winget later however.

**Comment by rashil2000** [comment]
Hi @ndbeals 

I'm sorry that you had to deal with Ash (that person is an utter asshole). 

The GitHub org had a makeover recently with new maintainers and has become very active now. I'd encourage you to make a PR again (no compulsion though 😅).

**Comment by ndbeals** [comment]
Hey @rashil2000 

I'm happy to hear the Org got a makeover, and I'd love to make a PR again! As long as I don't have to deal with Ash.

Are you one of the maintainers now? I'm not asking for you to accept the PR before it's even open, but I'd just like confirmation that having scoop add an autostart task for this service (which was the point of contention the first time) is now acceptable?

**Comment by rashil2000** [comment]
> Are you one of the maintainers now?

Yes.

> I'd just like confirmation that having scoop add an autostart task for this service (which was the point of contention the first time) is now acceptable?

Unfortunately, no (see https://github.com/ScoopInstaller/Scoop/issues/1526 and https://github.com/ScoopInstaller/Scoop/issues/2276). Scoop strives to be as portable and non-invasive as possible, and does not touch machine-specific stuff like registry and services by default. However, you're free to create as many shortcuts and helper scripts to make it easy for users to add startup programs themselves (the notes section will instruct them how).

> P.S: you reaching out like this goes a long way to restoring faith with scoop

Thank you for the kind words! Sadly, far far too many people have been discouraged due to Ash's childish behavior; it's going to be a long way to bring them all back :)

**Comment by ndbeals** [comment]
> Unfortunately, no (see ScoopInstaller/Scoop#1526 and ScoopInstaller/Scoop#2276). Scoop strives to be as portable and non-invasive as possible, and does not touch machine-specific stuff like registry and services by default.

Okay, that seems clear. And I've looked at those two linked issues, them both being stale for >2 years doesn't give me hope.

> However, you're free to create as many shortcuts and helper scripts

Okay so I need clarification, not trying to be pedantic, just want to get to the bottom of this. You can answer these with just yes/no if you want.

Having scoop creating shortcuts in the start menu is acceptable?

Fact: "Windows/Start Menu/autostart" is a standard location in Windows that automatically runs any shortcuts within it.

Can I have the scoop manifest automatically put a shortcut into that autorun folder?


If the answer to the previous question is no, what do you recommend for this situation with this app?

Keep in mind, this application has zero user interaction. It has no interface, no configuration file, 
and minimal CLI configuration (it has one flag that is not really ever used). It's meant to be started once at login, and forgotten about.

Does scoop support additional, custom installer queries/actions? I.E can I make scoop ask the user "would you like to install an autostart service for this application?"

**Comment by rashil2000** [comment]
> them both being stale for >2 years doesn't give me hope.

I will mention that since Scoop was abandoned, it was defunct for more than 2 years. We are getting around to solving issues (the issue count has gone down from 570 to 150 in the past 4 months :)).

> Having scoop creating shortcuts in the start menu is acceptable?

Yes. It already does that.

> Can I have the scoop manifest automatically put a shortcut into that autorun folder?

No.

> If the answer to the previous question is no, what do you recommend for this situation with this app?

Personally, I can recommend a tiny a batch/powershell script (which takes 2 arguments - /install and /uninstall, to enable and disable autostart respectively) which will be put in the [scripts](https://github.com/ScoopInstaller/Extras/tree/master/scripts) folder (you can have a look at many other helper scripts already present in that folder). When the installation of the app is complete, it can show a message "You can run the \<scriptname\> script to enable autostart" to the user.

> Does scoop support additional, custom installer queries/actions? I.E can I make scoop ask the user "would you like to install an autostart service for this application?"

Not yet. See https://github.com/ScoopInstaller/Scoop/issues/3736
